TRANSLATIONS = {
    "EN": {
        "app_title": "Ubuntu DNS Manager",
        "header": "DNS Manager Pro",
        "scan": "Network Status...",
        "conn_active": "Active: {}",
        "conn_none": "Disconnected",
        "refresh": "Refresh",
        "col_name": "Name",
        "col_ipv4": "IP Address",
        "col_ping": "Ping (ms)",
        "col_speed": "Dig (ms)",
        "btn_apply": "Apply DNS",
        "btn_del": "Delete Selected",
        "btn_clean": "Clean Dead",
        "btn_cond_del": "Manual Clean ▼",
        "opt_clean_settings": "Clean by Rules Now",
        "btn_update": "Update List",
        "btn_test": "Run Test",
        "menu_settings": "Settings & Language",
        "msg_apply": "DNS Applied Successfully!",
        "msg_del": "Deleted {} entries.",
        "msg_clean": "Auto-cleaned {} servers.",
        "msg_wait": "Processing...",
        "status_ready": "Ready.",
        "status_testing": "Testing {}/{}...",
        "err_perm": "Run as Root (sudo)!",
        "settings_title": "Settings",
        "lbl_urls": "Update URLs:",
        "lbl_domain": "Test Domain:",
        "lbl_limits": "Auto-Clean Rules (During Test):",
        "lbl_max_ping": "Max Ping (ms):",
        "lbl_max_speed": "Max Dig (ms):",
        "chk_auto_clean": "Enable Auto-Clean during test",
        "test_mode": "Test:",
        "confirm_del": "Delete selected items?"
    },
    "FA": {
        "app_title": "مدیریت DNS اوبونتو",
        "header": "مدیریت پیشرفته DNS",
        "scan": "وضعیت شبکه...",
        "conn_active": "متصل: {}",
        "conn_none": "قطع",
        "refresh": "بروزرسانی",
        "col_name": "نام سرویس",
        "col_ipv4": "آدرس IP",
        "col_ping": "پینگ (ms)",
        "col_speed": "سرعت Dig",
        "btn_apply": "اعمال DNS",
        "btn_del": "حذف انتخاب‌شده",
        "btn_clean": "حذف خراب‌ها",
        "btn_cond_del": "حذف دستی ▼",
        "opt_clean_settings": "حذف طبق قوانین (الان)",
        "btn_update": "دریافت آپدیت",
        "btn_test": "شروع تست",
        "menu_settings": "تنظیمات و زبان",
        "msg_apply": "DNS با موفقیت اعمال شد!",
        "msg_del": "تعداد {} مورد حذف شد.",
        "msg_clean": "تعداد {} سرور به صورت خودکار حذف شد.",
        "msg_wait": "لطفا صبر کنید...",
        "status_ready": "آماده.",
        "status_testing": "در حال تست {}/{}...",
        "err_perm": "لطفا با دسترسی روت (sudo) اجرا کنید!",
        "settings_title": "تنظیمات",
        "lbl_urls": "لینک‌های آپدیت:",
        "lbl_domain": "دامنه تست:",
        "lbl_limits": "قوانین حذف خودکار (هنگام تست):",
        "lbl_max_ping": "حداکثر پینگ:",
        "lbl_max_speed": "حداکثر زمان Dig:",
        "chk_auto_clean": "فعالسازی حذف خودکار هنگام تست",
        "test_mode": "نوع تست:",
        "confirm_del": "آیا مطمئن هستید؟"
    },
    "ZH": {
        "app_title": "Ubuntu DNS 管理器",
        "header": "DNS 管理器",
        "scan": "网络状态...",
        "conn_active": "活跃: {}",
        "conn_none": "未连接",
        "refresh": "刷新",
        "col_name": "名称",
        "col_ipv4": "IP 地址",
        "col_ping": "延迟 (ms)",
        "col_speed": "查询 (ms)",
        "btn_apply": "应用 DNS",
        "btn_del": "删除所选",
        "btn_clean": "清理无效",
        "btn_cond_del": "手动清理 ▼",
        "opt_clean_settings": "按规则清理",
        "btn_update": "更新列表",
        "btn_test": "运行测试",
        "menu_settings": "设置",
        "msg_apply": "DNS 已应用！",
        "msg_del": "已删除 {} 项。",
        "msg_clean": "自动清理完成。",
        "msg_wait": "处理中...",
        "status_ready": "就绪。",
        "status_testing": "测试中 {}/{}...",
        "err_perm": "请以 Root (sudo) 运行！",
        "settings_title": "配置",
        "lbl_urls": "更新 URL:",
        "lbl_domain": "测试域名:",
        "lbl_limits": "自动清理规则:",
        "lbl_max_ping": "最大延迟:",
        "lbl_max_speed": "最大查询:",
        "chk_auto_clean": "测试时启用自动清理",
        "test_mode": "测试模式:",
        "confirm_del": "删除所选项？"
    },
    "RU": {
        "app_title": "Менеджер DNS Ubuntu",
        "header": "Менеджер DNS",
        "scan": "Статус сети...",
        "conn_active": "Активно: {}",
        "conn_none": "Нет сети",
        "refresh": "Обновить",
        "col_name": "Имя",
        "col_ipv4": "IP Адрес",
        "col_ping": "Пинг (мс)",
        "col_speed": "Dig (мс)",
        "btn_apply": "Применить",
        "btn_del": "Удалить",
        "btn_clean": "Очистить",
        "btn_cond_del": "Очистка ▼",
        "opt_clean_settings": "Очистить по правилам",
        "btn_update": "Обновить",
        "btn_test": "Тест",
        "menu_settings": "Настройки",
        "msg_apply": "Применено!",
        "msg_del": "Удалено {}.",
        "msg_clean": "Авто-очистка выполнена.",
        "msg_wait": "Обработка...",
        "status_ready": "Готов.",
        "status_testing": "Тест {}/{}...",
        "err_perm": "Запустите через sudo!",
        "settings_title": "Настройки",
        "lbl_urls": "URL обновлений:",
        "lbl_domain": "Тест домен:",
        "lbl_limits": "Правила авто-очистки:",
        "lbl_max_ping": "Макс. Пинг:",
        "lbl_max_speed": "Макс. Dig:",
        "chk_auto_clean": "Вкл. авто-очистку при тесте",
        "test_mode": "Режим:",
        "confirm_del": "Удалить?"
    }
}

def get_text(lang_code, key):
    return TRANSLATIONS.get(lang_code, TRANSLATIONS["EN"]).get(key, key)